version: "3.7"

services:
    nginx:
        image: nginx:1.19
        ports:
            - "80:80"
        volumes:
            - ./viz/:/usr/share/nginx/html/viz/:ro
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - fuseki
    fuseki:
        image: stain/jena-fuseki:3.14.0
        environment: 
            - ADMIN_PASSWORD=nekodaisuki
            - VIRTUAL_HOST=${VIRTUAL_HOST:-localhost}
